services:
  coconet-headless:
    build: .
    environment:
      COCONET_HOME: /task-data/CoCoNet
      SSP: 1.9
      ENSEMBLE_RUNS: 1
      START_YEAR: 2015
      END_YEAR: 2017
      SAVE_YEAR: 2016
      PROJECTION_YEAR: 2016
      START_COTS_CONTROL: 9999
    volumes:
      - ./outputs:/task-data/CoCoNet/CoCoNet-model/outputs  #* optional - good for local (non ecs runs). ECS mount point is /task-data which encapsulates it all
      - ./CoCoNet-model:/task-data/CoCoNet/CoCoNet-model
      # - coconet-prefs:/task-data/CoCoNet/CoCoNet-model/.prefs/
      # todo - clear this before each run?
    # sleep test entrypoiont
    # entrypoint: ["sleep", "infinity"]

volumes:
  coconet-prefs: