services:
  coconet-headless:
    build: .
    environment:
      COCONET_HOME: /shared/CoCoNet
      MODEL_OUTPUT_DIR: "test-output-dir1"
      SSP: 1.9
      ENSEMBLE_RUNS: 1
      START_YEAR: 2015
      END_YEAR: 2017
      SAVE_YEAR: 2016
      PROJECTION_YEAR: 2016
      START_COTS_CONTROL: 9999
    volumes:
      - ./test-output-dir1:/shared/CoCoNet/CoCoNet-model/test-output-dir1 #* optional - good for local (non ecs runs). ECS mount point is /shared/CoCoNet which encapsulates it all
      - ./CoCoNet-model:/shared/CoCoNet/CoCoNet-model
      # - coconet-prefs:/shared/CoCoNet/CoCoNet-model/.prefs/
      # todo - clear this before each run?
    # sleep test entrypoiont
    # entrypoint: ["sleep", "infinity"]

volumes:
  coconet-prefs: